using System.Linq;
using System.Text;
using CsGrafeq.I18N.Generator.Properties;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CsGrafeq.I18N.Generator;

[Generator]
public class MultiLanguageResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resx = Resources.LanguageData.Replace("\r\n", "\n").Split('\n');
        var builder = new StringBuilder();
        var dicBuilder = new StringBuilder();
        builder.AppendLine("//加上此行以防止编译器进行不必要的代码分析，避免出现警告");
        builder.AppendLine("//<auto-generated>\r\n");
        builder.AppendLine("namespace CsGrafeq.I18N;\r\n");
        builder.AppendLine("public class MultiLanguageResources{");
        builder.AppendLine("\tpublic static MultiLanguageResources Instance { get; private set; } = new();");
        builder.AppendLine("\tpublic IReadOnlyDictionary<string, MultiLanguageData> All { get; init; }");
        var split = ',';
        var title = resx.Take(1).Single().Split(split).Skip(1).ToArray();
        var languages = title.Select(t => t.Split(';')[0]).ToArray();
        var languagesText = title.Select(t => t.Split(';')[1]).ToArray();
        foreach (var line in resx.Skip(1))
        {
            if (string.IsNullOrWhiteSpace(line)) continue;
            var parts = line.Split(split);
            if (parts.Length != 3) continue;
            var key = parts[0].Trim().Replace(" ", "").Replace("\t", "") + "Text";
            var s1 = parts[1].Trim();
            var s2 = parts[2].Trim();
            if (s1.Length * key.Length * s2.Length != 0)
            {
                builder.AppendLine(
                    $"\tpublic MultiLanguageData {key} {{ get; }} = new() {{ {languages[0]} = \"{s1}\", {languages[1]} = \"{s2}\" }};");
                dicBuilder.AppendLine($"\t\t\t[\"{key}\"] = {key},");
            }
            else
            {
                builder.AppendLine("//error:" + line);
            }
        }

        var en = Resources.README.Replace("\"", "\"\"");
        var zh = Resources.README_ZH.Replace("\"", "\"\"");
        builder.AppendLine(
            $"\tpublic MultiLanguageData ReadmeText {{ get; }} = new MultiLanguageData() {{ Chinese = @\"{zh}\", English = @\"{en}\" }};");


        builder.AppendLine("\tpublic MultiLanguageResources(){");
        builder.AppendLine("\t\tAll = new global::System.Collections.Generic.Dictionary<string, MultiLanguageData>{");
        builder.Append(dicBuilder);
        builder.AppendLine("\t\t};");
        builder.AppendLine("\t}");
        builder.AppendLine("}");
        var multiLanguageResources = builder.ToString().Replace("\t", "    ");

        builder.Clear();
        builder.AppendLine("using System;");
        builder.AppendLine("namespace CsGrafeq.I18N;");
        builder.AppendLine("public enum LanguagesEnum");
        builder.AppendLine("{");
        for (int i = 0; i < languages.Length; i++)
        {
            builder.AppendLine($"\t{languages[i]},");
        }
        builder.AppendLine("}");
        var languagesEnum = builder.ToString().Replace("\t", "    ");
        
        builder.Clear();
        dicBuilder.Clear();
        var dicBuilder2 = new StringBuilder();
        var dicBuilder3 = new StringBuilder();
        builder.AppendLine("using System;");
        builder.AppendLine("using ReactiveUI;");
        builder.AppendLine("namespace CsGrafeq.I18N;");
        builder.AppendLine("public partial class MultiLanguageData");
        builder.AppendLine("{");
        dicBuilder.AppendLine("\tpublic static readonly IReadOnlyList<string> LanguageNames = new[] {");
        dicBuilder2.AppendLine("\tpublic static readonly IReadOnlyList<string> LanguageTexts = new[] {");
        dicBuilder3.AppendLine("\tpublic string GetData(LanguagesEnum key){");
        dicBuilder3.AppendLine("\t\treturn key switch {");
        for (int i = 0; i < languages.Length; i++)
        {
            builder.AppendLine($"\tpublic string {languages[i]}");
            builder.AppendLine("\t{");
            builder.AppendLine($"\t\tget;");
            builder.AppendLine($"\t\tinit => this.RaiseAndSetIfChanged(ref field, value);");
            builder.AppendLine("\t}");
            dicBuilder.AppendLine($"\t\t\"{languages[i]}\",");
            dicBuilder2.AppendLine($"\t\t\"{languagesText[i]}\",");
            dicBuilder3.AppendLine($"\t\t\tLanguagesEnum.{languages[i]} => {languages[i]},");
        }
        dicBuilder.AppendLine("\t};");
        dicBuilder2.AppendLine("\t};");
        dicBuilder3.AppendLine("\t\t\t_ => throw new ArgumentOutOfRangeException(nameof(key), key, null),");
        dicBuilder3.AppendLine("\t\t};");
        dicBuilder3.AppendLine("\t}");
        builder.AppendLine(dicBuilder.ToString());
        builder.AppendLine(dicBuilder2.ToString());
        builder.AppendLine(dicBuilder3.ToString());
        builder.AppendLine("}");
        var multiLanguageData = builder.ToString().Replace("\t", "    ");
        
        
        //在编译时生成源代码
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("LanguagesEnum.g.cs", SourceText.From(languagesEnum, Encoding.UTF8));
            ctx.AddSource("MultilanguageData.g.cs", SourceText.From(multiLanguageData, Encoding.UTF8));
            ctx.AddSource("MultiLanguageResources.g.cs", SourceText.From(multiLanguageResources, Encoding.UTF8));
        });
    }
}