using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CsGrafeq.I18N.Generator;

[Generator]
public class MultiLanguageResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resx = Properties.Resources.LanguageData.Replace("\r\n","\n").Split('\n');
        StringBuilder builder = new StringBuilder();
        StringBuilder dicBuilder= new StringBuilder();
        builder.AppendLine("//加上此行以防止编译器进行不必要的代码分析，避免出现警告");
        builder.AppendLine("//<auto-generated>\r\n");
        builder.AppendLine("namespace CsGrafeq.I18N;\r\n");
        builder.AppendLine("public class MultiLanguageResources{");
        builder.AppendLine("\tpublic static MultiLanguageResources Instance { get; private set; } = new();");
        builder.AppendLine("\tpublic IReadOnlyDictionary<string, MultiLanguageData> All { get; init; }");
        var title = resx.Take(1).ToArray()[0].Split('|');
        foreach (var line in resx.Skip(1))
        {
            if (string.IsNullOrWhiteSpace(line)) continue;
            var parts = line.Split('|');
            if (parts.Length != 3) continue;
            var key = parts[0].Trim().Replace(" ","").Replace("\t","")+"Text";
            var s1 = parts[1].Trim();
            var s2 = parts[2].Trim();
            builder.AppendLine($"\tpublic MultiLanguageData {key} {{ get; }} = new() {{ {title[1]} = \"{s1}\", {title[2]} = \"{s2}\" }};");
            dicBuilder.AppendLine($"\t\t\t[\"{key}\"] = {key},");
        }
        builder.AppendLine("\tpublic MultiLanguageResources(){");
        builder.AppendLine("\t\tAll = new global::System.Collections.Generic.Dictionary<string, MultiLanguageData>{");
        builder.Append(dicBuilder.ToString());
        builder.AppendLine("\t\t};");
        builder.AppendLine("\t}");
        builder.AppendLine("}");

        //在编译时生成源代码
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("MultiLanguageResources.g.cs", SourceText.From(builder.ToString().Replace("\t","    "), Encoding.UTF8)));
    }
}