using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Resources;
using System.Text;

namespace CsGrafeq.I18N.Generator;

[Generator]
public class MultiLanguageResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        string[] resx = ["abc,ab,abc"];
        var builder = new StringBuilder();
        var dicBuilder = new StringBuilder();
        builder.AppendLine("//加上此行以防止编译器进行不必要的代码分析，避免出现警告");
        builder.AppendLine("//<auto-generated>\r\n");
        builder.AppendLine("namespace CsGrafeq.I18N;\r\n");
        builder.AppendLine("public class MultiLanguageResources{");
        builder.AppendLine("\tpublic static MultiLanguageResources Instance { get; private set; } = new();");
        builder.AppendLine("\tpublic IReadOnlyDictionary<string, MultiLanguageData> All { get; init; }");
        var split = resx.Take(1).Single().Single();
        var title = resx.Skip(1).Take(1).Single().Split(split);
        foreach (var line in resx.Skip(1))
        {
            if (string.IsNullOrWhiteSpace(line)) continue;
            var parts = line.Split(split);
            if (parts.Length != 3) continue;
            var key = parts[0].Trim().Replace(" ", "").Replace("\t", "") + "Text";
            var s1 = parts[1].Trim();
            var s2 = parts[2].Trim();
            if (s1.Length * key.Length * s2.Length != 0)
            {
                builder.AppendLine(
                    $"\tpublic MultiLanguageData {key} {{ get; }} = new() {{ {title[1]} = \"{s1}\", {title[2]} = \"{s2}\" }};");
                dicBuilder.AppendLine($"\t\t\t[\"{key}\"] = {key},");
            }
            else
            {
                builder.AppendLine("//error:" + line);
            }
        }

        builder.AppendLine("\tpublic MultiLanguageResources(){");
        builder.AppendLine("\t\tAll = new global::System.Collections.Generic.Dictionary<string, MultiLanguageData>{");
        builder.Append(dicBuilder);
        builder.AppendLine("\t\t};");
        builder.AppendLine("\t}");
        builder.AppendLine("}");

        //在编译时生成源代码
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("MultiLanguageResources.g.cs",
                SourceText.From(builder.ToString().Replace("\t", "    "), Encoding.UTF8)));
    }
}
/*using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Resources;
using System.Text;

namespace CsGrafeq.I18N.Generator;

[Generator]
public class MultiLanguageResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        string[] resx = ["abc,123,abc"];
        var builder = new StringBuilder();
        var dicBuilder = new StringBuilder();
        builder.AppendLine("//加上此行以防止编译器进行不必要的代码分析，避免出现警告");
        builder.AppendLine("//<auto-generated>\r\n");
        builder.AppendLine("namespace CsGrafeq.I18N;\r\n");
        builder.AppendLine("public class MultiLanguageResources{");
        builder.AppendLine("\tpublic static MultiLanguageResources Instance { get; private set; } = new();");
        builder.AppendLine("\tpublic IReadOnlyDictionary<string, MultiLanguageData> All { get; init; }");
        var split = resx.Take(1).Single().Single();
        var title = resx.Skip(1).Take(1).Single().Split(split);
        foreach (var line in resx.Skip(1))
        {
            if (string.IsNullOrWhiteSpace(line)) continue;
            var parts = line.Split(split);
            if (parts.Length != 3) continue;
            var key = parts[0].Trim().Replace(" ", "").Replace("\t", "") + "Text";
            var s1 = parts[1].Trim();
            var s2 = parts[2].Trim();
            if (s1.Length * key.Length * s2.Length != 0)
            {
                builder.AppendLine(
                    $"\tpublic MultiLanguageData {key} {{ get; }} = new() {{ {title[1]} = \"{s1}\", {title[2]} = \"{s2}\" }};");
                dicBuilder.AppendLine($"\t\t\t[\"{key}\"] = {key},");
            }
            else
            {
                builder.AppendLine("//error:" + line);
            }
        }

        builder.AppendLine("\tpublic MultiLanguageResources(){");
        builder.AppendLine("\t\tAll = new global::System.Collections.Generic.Dictionary<string, MultiLanguageData>{");
        builder.Append(dicBuilder);
        builder.AppendLine("\t\t};");
        builder.AppendLine("\t}");
        builder.AppendLine("}");

        //在编译时生成源代码
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("MultiLanguageResources.g.cs",
                SourceText.From(builder.ToString().Replace("\t", "    "), Encoding.UTF8)));
    }
}

/*using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CsGrafeq.TextGenerator;

[Generator]
public class TextGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var en = File.ReadAllText(new FileInfo("../../../README.md").FullName).Replace("\"", "\"\"");
        var zh = File.ReadAllText(new FileInfo("../../../README_ZH.md").FullName).Replace("\"", "\"\"");
        var builder = new StringBuilder();
        var dicBuilder = new StringBuilder();
        builder.AppendLine("//加上此行以防止编译器进行不必要的代码分析，避免出现警告");
        builder.AppendLine("//<auto-generated>\r\n");
        builder.AppendLine("namespace CsGrafeq;\r\n");
        builder.AppendLine("public class TextResources{");
        builder.AppendLine("\tpublic static TextResources Instance { get; private set; } = new();");
        builder.AppendLine("\tprivate TextResources(){}");
        builder.AppendLine($"\tpublic MultiLanguageData ReadmeText {{ get; }} = new MultiLanguageData() {{ Chinese = @\"{zh}\", English = @\"{en}\" }};");
        builder.AppendLine("}");

        //在编译时生成源代码
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("TextResources.g.cs",
                SourceText.From(builder.ToString().Replace("\t", "    "), Encoding.UTF8)));
    }
}*/