using CsGrafeq.Setting.Generator.Properties;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.IO;
using System.Linq;
using System.Text;

namespace CsGrafeq.Setting.Generator;

[Generator]
public class SettingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        string resx = Resources.SettingData??"";
        //var resx = "#";
        var parts=resx.Split('#');
        if (parts.Length!=2)
            throw new InvalidOperationException("Setting.txt 的内容格式不正确，必须包含两个 '#' 作为段落分隔符。");
        var usings=parts[0].Replace(" ", "").Replace("\r\n", "\n").Split('\n');
        var properties=parts[1].Replace(" ", "").Replace("\r\n", "\n").Split('\n');
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 由 SettingGenerator 生成");
        sb.AppendLine();
        foreach (var u in usings.Distinct())
        {
            if (!string.IsNullOrWhiteSpace(u))
                sb.AppendLine($"using {u};");
        }
        sb.AppendLine();

        sb.AppendLine($"namespace CsGrafeq.Setting;");
        sb.AppendLine("public partial class Setting");
        sb.AppendLine("{");
        foreach (var property in properties)
        {
            if(string.IsNullOrWhiteSpace(property))
                continue;
            var ps=property.Split(',');
            if (ps.Length != 3)
            {
                sb.AppendLine("    // wrong data:"+property);
                continue;
            }

            sb.AppendLine($"    public {ps[0]} {ps[1]}");
            sb.AppendLine("    {");
            sb.AppendLine("        get;");
            sb.AppendLine("        set => this.RaiseAndSetIfChanged(ref field, value);");
            sb.AppendLine($"    }}={ps[2]};");
            sb.AppendLine();
        }
        sb.AppendLine("}");
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("Setting.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8)));
    }

}