//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsGrafeq.Setting.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsGrafeq.Setting.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReactiveUI
        ///CsGrafeq.MVVM
        ///System
        ///SkiaSharp
        ///#
        ///uint,PrimaryColor,0xFF77CCBB
        ///byte,DefaultOpacity,255
        ///bool,EnableExpressionSimplification,false
        ///bool,MoveOptimization,false
        ///bool,ZoomOptimization,false
        ///bool,MoveOptimizationUserEnabled,true
        ///bool,ZoomOptimizationUserEnabled,true
        ///bool,ShowKeyboard,true
        ///bool,ShowAxes,true
        ///bool,ShowAxesNumber,true
        ///bool,ShowAxesMajorGrid,true
        ///bool,ShowAxesMinorGrid,true
        ///int,ClientSizeWidth,800
        ///int,ClientSizeHeight,600
        ///SKBlendMode,CompoundBlendMode,SKBlendMode.SrcOver        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingData {
            get {
                return ResourceManager.GetString("SettingData", resourceCulture);
            }
        }
    }
}
