//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsGrafeq.I18N.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsGrafeq.I18N.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///Key,Chinese,English
        ///Red,红色,Red
        ///Pink,粉色,Pink
        ///Purple,紫色,Purple
        ///DeepPurple,深紫色,Deep Purple
        ///Indigo,靛蓝色,Indigo
        ///Blue,蓝色,Blue
        ///LightBlue,浅蓝色,Light Blue
        ///Cyan,青色,Cyan
        ///Teal,蓝绿色,Teal
        ///Green,绿色,Green
        ///LightGreen,浅绿色,Light Green
        ///Lime,酸橙色,Lime
        ///Yellow,黄色,Yellow
        ///Amber,琥珀色,Amber
        ///Orange,橙色,Orange
        ///DeepOrange,深橙色,Deep Orange
        ///Brown,棕色,Brown
        ///Grey,灰色,Grey
        ///BlueGrey,蓝灰色,Blue Grey
        ///Light,亮色,Light
        ///Dark,暗色,Dark
        ///FollowSystem,跟随系统,Follow System
        ///Angle,角,Angle
        ///Unmovable,无法移动,Unmovable
        ///Circle,圆,Circle
        ///CsGrafeq,CsGr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LanguageData {
            get {
                return ResourceManager.GetString("LanguageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English](README.md)|[中文](README_ZH.md)
        ///
        ///# CsGrafeq
        ///![](https://img.shields.io/github/forks/jyswjjgdwtdtj/CsGrafeq?style=social)
        ///![](https://img.shields.io/github/watchers/jyswjjgdwtdtj/CsGrafeq?style=social )
        ///![](https://img.shields.io/github/stars/jyswjjgdwtdtj/CsGrafeq?color=green&amp;style=social)
        ///## Description
        ///
        ///CsGrafeq is a geometry sketchpad. It&apos;s made by Avalonia and use Material.Avalonia as its theme. 
        ///
        ///For the sake that JIT is unavailable in mobile platforms and browser, CsGrafeq now only s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string README {
            get {
                return ResourceManager.GetString("README", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [English](README.md)|[中文](README_ZH.md)
        ///
        ///# CsGrafeq
        ///![](https://img.shields.io/github/forks/jyswjjgdwtdtj/CsGrafeq?style=social)
        ///![](https://img.shields.io/github/watchers/jyswjjgdwtdtj/CsGrafeq?style=social )
        ///![](https://img.shields.io/github/stars/jyswjjgdwtdtj/CsGrafeq?color=green&amp;style=social)
        ///## 简介
        ///
        ///CsGrafeq是一项用C#实现的开源几何画板，使用Avalonia作为UI框架，Material.Avalonia作为主题。
        ///
        ///出于JIT在移动平台和浏览器中无法使用，CsGrafeq暂时只支持桌面端（目前仅支持Windows平台）
        ///
        ///[旧版本项目](./OldVersion/README.md) 是专为隐函数制作的，其更为稳定，但不代表其效果更好。
        ///
        ///![image](Exam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string README_ZH {
            get {
                return ResourceManager.GetString("README_ZH", resourceCulture);
            }
        }
    }
}
