//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsGrafeq.I18N.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsGrafeq.I18N.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///Key,Chinese,English
        ///Red,红色,Red
        ///Pink,粉色,Pink
        ///Purple,紫色,Purple
        ///DeepPurple,深紫色,Deep Purple
        ///Indigo,靛蓝色,Indigo
        ///Blue,蓝色,Blue
        ///LightBlue,浅蓝色,Light Blue
        ///Cyan,青色,Cyan
        ///Teal,蓝绿色,Teal
        ///Green,绿色,Green
        ///LightGreen,浅绿色,Light Green
        ///Lime,酸橙色,Lime
        ///Yellow,黄色,Yellow
        ///Amber,琥珀色,Amber
        ///Orange,橙色,Orange
        ///DeepOrange,深橙色,Deep Orange
        ///Brown,棕色,Brown
        ///Grey,灰色,Grey
        ///BlueGrey,蓝灰色,Blue Grey
        ///Light,亮色,Light
        ///Dark,暗色,Dark
        ///FollowSystem,跟随系统,Follow System
        ///Angle,角,Angle
        ///Unmovable,无法移动,Unmovable
        ///Circle,圆,Circle
        ///CsGrafeq,几何画板 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LanguageData {
            get {
                return ResourceManager.GetString("LanguageData", resourceCulture);
            }
        }
    }
}
