//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsGrafeq.I18N.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsGrafeq.I18N.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ,
        ///Key,Chinese,English
        ///Red,红色,Red
        ///Pink,粉色,Pink
        ///Purple,紫色,Purple
        ///DeepPurple,深紫色,Deep Purple
        ///Indigo,靛蓝色,Indigo
        ///Blue,蓝色,Blue
        ///LightBlue,浅蓝色,Light Blue
        ///Cyan,青色,Cyan
        ///Teal,蓝绿色,Teal
        ///Green,绿色,Green
        ///LightGreen,浅绿色,Light Green
        ///Lime,酸橙色,Lime
        ///Yellow,黄色,Yellow
        ///Amber,琥珀色,Amber
        ///Orange,橙色,Orange
        ///DeepOrange,深橙色,Deep Orange
        ///Brown,棕色,Brown
        ///Grey,灰色,Grey
        ///BlueGrey,蓝灰色,Blue Grey
        ///Light,亮色,Light
        ///Dark,暗色,Dark
        ///FollowSystem,跟随系统,Follow System
        ///Angle,角,Angle
        ///Unmovable,无法移动,Unmovable
        ///Circle,圆,Circle
        ///CsGrafeq,几何画板 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LanguageData {
            get {
                return ResourceManager.GetString("LanguageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [English](README.md)|[中文](README_ZH.md)
        ///
        ///# CsGrafeq
        ///![](https://img.shields.io/github/forks/jyswjjgdwtdtj/CsGrafeq?style=social)
        ///![](https://img.shields.io/github/watchers/jyswjjgdwtdtj/CsGrafeq?style=social )
        ///![](https://img.shields.io/github/stars/jyswjjgdwtdtj/CsGrafeq?color=green&amp;style=social)
        ///## Description
        ///
        ///CsGrafeq is a geometry sketchpad. It&apos;s made by Avalonia and use Material.Avalonia as its theme. 
        ///
        ///For the sake that JIT is unavailable in mobile platforms and browser, CsGrafeq now only s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string README {
            get {
                return ResourceManager.GetString("README", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [English](README.md)|[中文](README_ZH.md)
        ///
        ///# CsGrafeq
        ///![](https://img.shields.io/github/forks/jyswjjgdwtdtj/CsGrafeq?style=social)
        ///![](https://img.shields.io/github/watchers/jyswjjgdwtdtj/CsGrafeq?style=social )
        ///![](https://img.shields.io/github/stars/jyswjjgdwtdtj/CsGrafeq?color=green&amp;style=social)
        ///## 简介
        ///
        ///CsGrafeq是一项用C#实现的开源几何画板，使用Avalonia作为UI框架，Material.Avalonia作为主题。
        ///
        ///出于JIT在移动平台和浏览器中无法使用，CsGrafeq暂时只支持桌面端（目前仅支持Windows平台）
        ///
        ///[旧版本项目](./OldVersion/README.md) 是专为隐函数制作的，这项功能将会在未来合并入CsGrafeq。
        ///
        ///![image] [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string README_ZH {
            get {
                return ResourceManager.GetString("README_ZH", resourceCulture);
            }
        }
    }
}
